BlogCMS/Controllers/BlogController.cs
using BlogCMS.Data;
using BlogCMS.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogCMS.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Details(int id)
        {
            var repo = new BlogPostRepo();
            var post = repo.GetBlogPostById(id);

            return View(post);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int BlogId)
        {
            var repo = new BlogPostRepo();
            var post = repo.GetBlogPostById(BlogId);

            return View(post);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult Edit(BlogPost post)
        {
            var repo = new BlogPostRepo();
            repo.EditBlogPost(post);
            ViewBag.Message = "The post has been edited successfully.";
            return View("Success");
        }

        [Authorize]
        public ActionResult Add()
        {
            CategoryRepo repo = new CategoryRepo();
            List<Category> categories = repo.GetAllCategories();

            AddPostVM vm = new AddPostVM();
            vm.CreateCategoryList(categories);

            return View(vm);
        }

        [HttpPost]
        [Authorize]
        [ValidateInput(false)]
        public ActionResult AddBlog(AddPostVM vm)
        {
            var time = DateTime.Now;
            vm.BlogPost.DatePosted = time.Date;

            var repo = new BlogPostRepo();
            repo.AddBlogPost(vm.BlogPost);

            int blogId = repo.GetBlogId();
            repo.AddToArchieve(blogId);

            if (User.IsInRole("Admin"))
            {
                ViewBag.Message = "Your new post has been added. Don't forget to publish it so that your users can see it.";
            }
            else
            {
                ViewBag.Message = "Your new post has been submitted for Admin approval. Thanks!";
            }
            
            //return RedirectToAction("Index", "Home");
            return View("Success");
        }

        //public ActionResult Add()
        //{

        //    var repo = new BlogPostRepo();
        //    var post = new BlogPost();

        //    return View(post);
        //}

        //[HttpPost]
        //[ValidateInput(false)]
        //public ActionResult Add(BlogPost p)
        //{
        //    var time = DateTime.Now;
        //    p.DatePosted = time.Date;
        //    var repo = new BlogPostRepo();
        //    repo.AddBlogPost(p);

        //    return View();
        //}

        //public ActionResult Remove()
        //{

        //    //var repo = new BlogPostRepo();
        //    var post = new BlogPost();

        //    return View(post);
        //}

        //[Authorize]
        //[ValidateInput(false)]
        [Authorize(Roles = "Admin")]
        public ActionResult Remove(int blogpostId)
        {
            var repo = new BlogPostRepo();
            repo.RemoveBlogPost(blogpostId);

            ViewBag.Message = "The post has been deleted. It is still available in Archives.";
            return View("Success");
        }

        [Authorize]
        public ActionResult AddCategory()
        {
            var crepo = new CategoryRepo();
            var list = crepo.GetAllCategories();
            return View(list);

        }

        [HttpPost]
        [Authorize]
        public ActionResult AddCategory(string Category)
        {
            var crepo = new CategoryRepo();
            crepo.AddCategory(Category);
            var list = crepo.GetAllCategories();
            return View(list);
        }
    }
}

BlogCMS/Controllers/StaticPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogCMS.Model;
using BlogCMS.Data;

namespace BlogCMS.Controllers
{
    public class StaticPageController : Controller
    {
        // GET: Page
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddStatic()
        {
            var model = new StaticPage();

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult AddStatic(StaticPage page)
        {
            var brepo = new BlogPostRepo();
            brepo.AddStaticPage(page);
            ViewBag.Message = "A new static page has been added.";
            return View("Success");
        }

        //[Authorize(Roles = "Admin")]
        public ActionResult Show(int id)
        {
            var brepo = new BlogPostRepo();
            var page = brepo.GetPageById(id);

            return View(page);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Deactivate(int id)
        {
            var brepo = new BlogPostRepo();
            brepo.DeactivatePageById(id);

            return RedirectToAction("ManagePages", "Admin");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Activate(int id)
        {
            var brepo = new BlogPostRepo();
            brepo.ActivatePageById(id);

            return RedirectToAction("ManagePages", "Admin");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var brepo = new BlogPostRepo();
            var post = brepo.GetPageById(id);

            return View(post);

        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateInput(false)]
        public ActionResult Edit(StaticPage page)
        {
            var brepo = new BlogPostRepo();
            brepo.UpdatePage(page);
            ViewBag.Message = "The static page has been edited successfully.";
            return View("Success");
            //return RedirectToAction("ManagePages", "Admin");
        }
    }
}

BlogCMS/Views/Admin/Category.cshtml
@{
    ViewBag.Title = "Category";
}

<p>
    <label>Enter new Category:</label>
    <input type="text" id="Category" name="Category" />

    <button id="AddCategory" class="btn btn-primary">Add</button>
</p>
<div id="Result"></div>
<div id="Message"></div>

@*<script>
        $(document).ready(function () {
            ShowCategoryList();

            $("#AddCategory").on('click', function () {
                AddCategory();
            });
        });

        function ShowCategoryList() {
            $.getJSON("/API/CategoryAPI/", null).done(function (data) {
                $("#Result").html(createTable(data));
            }).fail(function () {
                $("#Result").html("<p>The category list cannot be loaded.</p>");
            });
        }

        function AddCategory() {
            var URL = "/API/CategoryAPI/";

            $.ajax({
                type: "Post",
                url: URL,
                datatype: "json",
                success: function(newcategory) {
                    $("#Result").html(createTable(data));
                    var message = "<h3>Category " + $("#Category").val() + " is added.</h3>";
                    $("#Message").html(message);
                    $("#Category").val("");
                },
                fail: function() {
                    $("#Result").html("<p>The category cannot be added.</p>");
                },
                data: { category : $("#Category").val()}
            });
        }

        //function AddCategory() {
        //    $.getJSON("/Policy/AddCategoryJ/", { category: $("#Category").val() }).done(function (data) {
        //        $("#Result").html(createTable(data));
        //        var message = "<h3>Category " + $("#Category").val() + " is added.</h3>";
        //        $("#Message").html(message);
        //        $("#Category").val("");
        //    }).fail(function () {
        //        $("#Result").html("<p>The category list cannot be loaded.</p>");
        //    });
        //}

        function createTable(data) {
            var results = "";
            var rowcounter = 1;
            results += "<table>";
            results += "<tr><th>Category</th></tr>";
            $.each(data, function () {
                if (rowcounter % 2 == 1) {
                    results += "<tr class=\"odd\"><td>";
                } else {
                    results += "<tr class=\"even\"><td>";
                }
                results += this.CategoryName;
                results += "</td></tr>";
                rowcounter++;
            });
            results += "</table>";

            return results;
        }

</script>*@
@section scripts
{
    
    <script src="~/Scripts/Views/Category.js"></script>

}

BlogCMS/Views/Admin/Index.cshtml
@using BlogCMS.Model
@model List<BlogPost>

@{
    ViewBag.Title = "Index";
}

<h2>Admin Portal</h2>

<div class="row">
    <table class="table table-bordered" data-height="299" data-row-style="rowStyle" style="margin-top: 10px">
        <thead style="background-color: #f5f5f5">
            <tr>
                <th style="padding-right: 5px">Blog ID</th>
                <th style="padding-right: 5px">Blog Title</th>
                <th style="padding-right: 5px">Status</th>
                <th>Action</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var post in Model)
            {
                <tr>
                    <td>@post.BlogID</td>
                    <td>@Html.ActionLink(@post.Title, "Details", "Blog", new { id = post.BlogID }, null)</td>
                    @if (post.StatusID == 2)
                    {
                        <td>Published</td>
                    }
                    else if(post.StatusID == 1)
                    {
                        <td>Pending</td>
                    }
                    else if (post.StatusID == 4)
                    {
                        <td>Expired</td>
                    }
                    else
                    {
                        <td>Archived</td>
                    }

                    @if (post.StatusID == 1)
                    {
                        <td>
                            @Html.ActionLink("Publish", "Publish", "Admin", new { id = post.BlogID }, new { @class = "btn btn-primary btn-large" })
                        </td>
                    }
                    else if (post.StatusID == 2)
                    {
                        <td>
                            @Html.ActionLink("Unpublish", "Unpublish", "Admin", new { id = post.BlogID }, new { @class = "btn btn-primary btn-large" })
                        </td>
                    }
                    else if (post.StatusID == 4)
                    {
                        <td>
                          
                        </td>
                    }
                    else if (post.StatusID == 5)
                    {
                        <td>
                            @Html.ActionLink("Publish", "Publish", "Admin", new { id = post.BlogID }, new { @class = "btn btn-primary btn-large" })
                        </td>
                    }
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Blog", new { BlogId = post.BlogID }, new { @class = "btn btn-default btn-large" })
                    </td>
                    <td>
                        @Html.ActionLink("Remove", "Remove", "Blog", new { blogpostId = post.BlogID }, new { @class = "btn btn-default btn-large" })
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

BlogCMS/Views/Admin/ManagePages.cshtml
@using BlogCMS.Model
@model List<StaticPage>

<div class="row">
    <table class="table table-bordered" data-height="299" data-row-style="rowStyle" style="margin-top: 10px">
        <thead style="background-color: #f5f5f5">
            <tr>
                <th style="padding-right: 5px">Page ID</th>
                <th style="padding-right: 5px">Page Title</th>
                <th style="padding-right: 5px">Active</th>
                <th>Activate/Deactivate</th>
                <th>Edit </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var post in Model)
            {
                <tr>
                    <td>@post.StaticPageID</td>
                    <td>@Html.ActionLink(post.Title, "Show", "StaticPage", new { id = post.StaticPageID }, null)</td>
                    @if (post.Active == true)
                    {
                        <td>Active</td>
                    }
                    else
                    {
                        <td>Deactivated</td>
                    }

                    @if (post.Active == true)
                    {
                        <td>
                            @Html.ActionLink("Deactivate", "Deactivate", "StaticPage", new { id = post.StaticPageID }, new { @class = "btn btn-primary btn-large" })
                        </td>
                    }
                    else if (post.Active == false)
                    {
                        <td>
                            @Html.ActionLink("Activate", "Activate", "StaticPage", new { id = post.StaticPageID }, new { @class = "btn btn-primary btn-large" })
                        </td>
                    }
            
                    <td>
                        @Html.ActionLink("Edit", "Edit", "StaticPage", new { id = post.StaticPageID }, new { @class = "btn btn-default btn-large" })
                    </td>
                    

                </tr>
            }
        </tbody>
    </table>
</div>